-- Seed incidents for 2025-2026 Nigerian security events
-- Run with: psql $DATABASE_URL -f seed-incidents-2025.sql

-- Clear existing incidents
DELETE FROM incidents;

-- Reset the sequence
SELECT setval('incidents_id_seq', 1, false);

INSERT INTO incidents (title, description, location, region, state, lga, severity, status, reported_at, reported_by, coordinates, category, impacted_population, verification_status, reporting_method) VALUES

-- January 2025
('Bandit Attack on Zamfara Village', 'Armed bandits attacked Anka community in Zamfara State, killing several residents and displacing hundreds. Security forces deployed to the area.', 'Gusau, Zamfara', 'North West', 'Zamfara', 'Gusau', 'critical', 'resolved', '2025-01-05 08:30:00', 1, '{"lat":12.1704,"lng":6.6642}', 'violence', 15000, 'verified', 'text'),
('Flooding in Bayelsa Communities', 'Heavy rainfall caused severe flooding in Yenagoa and surrounding areas, submerging homes and farmlands. Over 2,000 families displaced.', 'Yenagoa, Bayelsa', 'South South', 'Bayelsa', 'Yenagoa', 'high', 'resolved', '2025-01-08 14:15:00', 1, '{"lat":4.9267,"lng":6.2676}', 'natural_disaster', 12000, 'verified', 'text'),
('Farmer-Herder Clash in Benue', 'Violent confrontation between farmers and Fulani herders in Makurdi LGA over grazing land. Several casualties reported on both sides.', 'Makurdi, Benue', 'North Central', 'Benue', 'Makurdi', 'high', 'resolved', '2025-01-12 06:45:00', 1, '{"lat":7.7322,"lng":8.5391}', 'conflict', 8000, 'verified', 'text'),
('Protest Against Fuel Price Hike in Lagos', 'Thousands of residents took to the streets in Lagos to protest rising fuel prices. Police used tear gas to disperse the crowd near Ikeja.', 'Ikeja, Lagos', 'South West', 'Lagos', 'Ikeja', 'medium', 'resolved', '2025-01-15 10:00:00', 1, '{"lat":6.5964,"lng":3.3425}', 'protest', 50000, 'verified', 'web_form'),
('Kidnapping of Travelers on Kaduna-Abuja Highway', 'Armed gunmen ambushed and kidnapped 15 travelers along the Kaduna-Abuja highway. Ransom demands issued to families.', 'Kaduna North, Kaduna', 'North West', 'Kaduna', 'Kaduna North', 'critical', 'resolved', '2025-01-18 16:30:00', 1, '{"lat":10.5167,"lng":7.4333}', 'kidnapping', 500, 'verified', 'text'),
('Market Fire in Onitsha', 'A massive fire engulfed the main market in Onitsha, destroying goods worth billions of naira. No casualties reported but hundreds of traders affected.', 'Onitsha, Anambra', 'South East', 'Anambra', 'Onitsha', 'high', 'resolved', '2025-01-22 03:20:00', 1, '{"lat":6.1495,"lng":6.7882}', 'economic', 25000, 'verified', 'text'),

-- February 2025
('Boko Haram Ambush in Borno', 'Boko Haram fighters ambushed a military convoy near Bama, Borno State. Several soldiers killed and vehicles destroyed.', 'Bama, Borno', 'North East', 'Borno', 'Bama', 'critical', 'active', '2025-02-02 07:00:00', 1, '{"lat":11.5204,"lng":13.6896}', 'terrorism', 3000, 'verified', 'text'),
('Oil Pipeline Vandalism in Rivers', 'Militants vandalized a major oil pipeline in Obio-Akpor LGA, causing a significant oil spill and environmental damage to surrounding communities.', 'Obio-Akpor, Rivers', 'South South', 'Rivers', 'Obio-Akpor', 'high', 'resolved', '2025-02-06 11:30:00', 1, '{"lat":4.8896,"lng":6.9569}', 'economic', 18000, 'verified', 'text'),
('Student Protest at University of Ibadan', 'Students of the University of Ibadan protested over unpaid bursaries and poor hostel conditions. University gates were blocked for hours.', 'Ibadan North, Oyo', 'South West', 'Oyo', 'Ibadan North', 'low', 'resolved', '2025-02-10 09:00:00', 1, '{"lat":7.3775,"lng":3.9470}', 'protest', 15000, 'verified', 'web_form'),
('Building Collapse in Lagos Island', 'A three-story building collapsed in Lagos Island trapping at least 12 people. Rescue operations ongoing with emergency services on scene.', 'Lagos Island, Lagos', 'South West', 'Lagos', 'Lagos Island', 'critical', 'resolved', '2025-02-14 13:45:00', 1, '{"lat":6.4541,"lng":3.3947}', 'infrastructure', 2000, 'verified', 'text'),
('Communal Clash in Plateau State', 'Ethnic violence erupted in Jos South between rival communities, resulting in deaths and destruction of property. Curfew imposed.', 'Jos South, Plateau', 'North Central', 'Plateau', 'Jos South', 'high', 'resolved', '2025-02-18 05:30:00', 1, '{"lat":9.8675,"lng":8.8961}', 'conflict', 20000, 'verified', 'text'),
('Cholera Outbreak in Adamawa', 'Cholera outbreak reported in Yola North LGA with over 200 confirmed cases. Health authorities mobilizing response teams.', 'Yola North, Adamawa', 'North East', 'Adamawa', 'Yola North', 'critical', 'resolved', '2025-02-22 08:00:00', 1, '{"lat":9.2094,"lng":12.4807}', 'natural_disaster', 35000, 'verified', 'text'),

-- March 2025
('Armed Robbery at Bank in Aba', 'Armed robbers attacked a commercial bank in Aba North, carting away an undisclosed amount. Two security guards killed in the attack.', 'Aba North, Abia', 'South East', 'Abia', 'Aba North', 'high', 'resolved', '2025-03-03 15:00:00', 1, '{"lat":5.1215,"lng":7.3698}', 'violence', 5000, 'verified', 'text'),
('Erosion Threatens Homes in Anambra', 'Severe gully erosion in Awka threatening over 500 homes. Government declared state of emergency in affected communities.', 'Awka, Anambra', 'South East', 'Anambra', 'Awka', 'high', 'active', '2025-03-07 10:30:00', 1, '{"lat":6.2104,"lng":7.0719}', 'natural_disaster', 8000, 'verified', 'text'),
('Political Violence in Kano', 'Clashes between supporters of rival political parties in Kano Municipal area. Multiple injuries reported and property destroyed.', 'Kano Municipal, Kano', 'North West', 'Kano', 'Kano Municipal', 'high', 'resolved', '2025-03-11 12:00:00', 1, '{"lat":12.0022,"lng":8.5920}', 'political', 30000, 'verified', 'text'),
('Highway Accident in Ogun', 'Multiple vehicle pile-up on Lagos-Abeokuta expressway involving a tanker and three buses. Over 20 casualties.', 'Abeokuta, Ogun', 'South West', 'Ogun', 'Abeokuta', 'critical', 'resolved', '2025-03-15 06:15:00', 1, '{"lat":7.1475,"lng":3.3619}', 'infrastructure', 1000, 'verified', 'text'),
('ISWAP Attack on Yobe Town', 'Islamic State West Africa Province fighters stormed a town in Damaturu LGA, engaging military in heavy gunfight.', 'Damaturu, Yobe', 'North East', 'Yobe', 'Damaturu', 'critical', 'active', '2025-03-20 04:00:00', 1, '{"lat":11.7471,"lng":11.9609}', 'terrorism', 10000, 'verified', 'text'),
('Gender-Based Violence Report in Enugu', 'Multiple cases of domestic violence reported in Enugu North. NGOs calling for stronger intervention and support services.', 'Enugu North, Enugu', 'South East', 'Enugu', 'Enugu North', 'medium', 'active', '2025-03-25 09:00:00', 1, '{"lat":6.4402,"lng":7.4994}', 'sgbv', 2500, 'partially_verified', 'voice'),

-- April 2025
('Cult Clash in Benin City', 'Rival cult groups clashed in Benin City leaving five dead and several injured. Police arrested multiple suspects.', 'Benin City, Edo', 'South South', 'Edo', 'Benin City', 'high', 'resolved', '2025-04-02 22:00:00', 1, '{"lat":6.3350,"lng":5.6037}', 'violence', 15000, 'verified', 'text'),
('Drought Emergency in Sokoto', 'Prolonged drought in Sokoto North affecting farming communities. Crop failures leading to food insecurity for thousands.', 'Sokoto North, Sokoto', 'North West', 'Sokoto', 'Sokoto North', 'high', 'active', '2025-04-05 08:00:00', 1, '{"lat":13.0622,"lng":5.2339}', 'natural_disaster', 45000, 'verified', 'text'),
('Workers Strike in Port Harcourt', 'Oil workers in Port Harcourt went on indefinite strike over unpaid wages and poor working conditions. Production halted at several facilities.', 'Port Harcourt, Rivers', 'South South', 'Rivers', 'Port Harcourt', 'medium', 'resolved', '2025-04-08 07:00:00', 1, '{"lat":4.8156,"lng":7.0498}', 'protest', 20000, 'verified', 'web_form'),
('Kidnapping of School Children in Niger State', 'Gunmen abducted 30 students from a secondary school in Minna. Military launched search and rescue operation.', 'Minna, Niger', 'North Central', 'Niger', 'Minna', 'critical', 'resolved', '2025-04-12 10:30:00', 1, '{"lat":9.6138,"lng":6.5569}', 'kidnapping', 5000, 'verified', 'text'),
('Power Grid Collapse Nationwide', 'National power grid collapsed for the third time in April, plunging major cities into darkness. Businesses and hospitals severely affected.', 'Lagos Island, Lagos', 'South West', 'Lagos', 'Lagos Island', 'high', 'resolved', '2025-04-15 14:00:00', 1, '{"lat":6.4541,"lng":3.3947}', 'infrastructure', 200000, 'verified', 'text'),
('Land Dispute Violence in Nasarawa', 'Violent land dispute between two clans in Lafia resulted in the burning of houses and displacement of families.', 'Lafia, Nasarawa', 'North Central', 'Nasarawa', 'Lafia', 'high', 'resolved', '2025-04-20 05:00:00', 1, '{"lat":8.4939,"lng":8.5211}', 'conflict', 7000, 'verified', 'text'),
('Sexual Assault Cases Spike in FCT', 'Alarming increase in reported sexual assault cases in Abuja Municipal. Advocacy groups demand immediate government response.', 'Abuja Municipal, FCT', 'North Central', 'FCT', 'Abuja Municipal', 'high', 'active', '2025-04-25 11:00:00', 1, '{"lat":9.0765,"lng":7.3986}', 'sgbv', 3000, 'partially_verified', 'text'),

-- May 2025
('Tanker Explosion on Otedola Bridge Lagos', 'A fuel tanker exploded on Otedola Bridge along Lagos-Ibadan expressway, destroying over 20 vehicles. Multiple fatalities confirmed.', 'Ikeja, Lagos', 'South West', 'Lagos', 'Ikeja', 'critical', 'resolved', '2025-05-03 02:30:00', 1, '{"lat":6.5964,"lng":3.3425}', 'infrastructure', 5000, 'verified', 'text'),
('Bandit Raid in Katsina Villages', 'Armed bandits raided multiple villages in Katsina LGA, looting homes and abducting women and children. Military deployed.', 'Katsina, Katsina', 'North West', 'Katsina', 'Katsina', 'critical', 'active', '2025-05-07 03:00:00', 1, '{"lat":12.9908,"lng":7.6008}', 'violence', 12000, 'verified', 'text'),
('Anti-Tax Protest in Ibadan', 'Market traders in Ibadan staged a massive protest against new state tax policies, blocking major roads and disrupting commerce.', 'Ibadan North, Oyo', 'South West', 'Oyo', 'Ibadan North', 'medium', 'resolved', '2025-05-10 08:30:00', 1, '{"lat":7.3775,"lng":3.9470}', 'protest', 40000, 'verified', 'web_form'),
('Ethnic Violence in Taraba', 'Inter-ethnic clash in Jalingo between Tiv and Jukun communities over chieftaincy dispute. Several killed and properties burned.', 'Jalingo, Taraba', 'North East', 'Taraba', 'Jalingo', 'high', 'resolved', '2025-05-14 06:00:00', 1, '{"lat":8.8932,"lng":11.3598}', 'conflict', 15000, 'verified', 'text'),
('Windstorm Destroys Homes in Bauchi', 'Severe windstorm in Bauchi LGA destroyed over 300 homes and uprooted trees. Several people injured, emergency response activated.', 'Bauchi, Bauchi', 'North East', 'Bauchi', 'Bauchi', 'high', 'resolved', '2025-05-18 16:00:00', 1, '{"lat":10.3158,"lng":9.8442}', 'natural_disaster', 8000, 'verified', 'text'),
('Assassination Attempt on Politician in Abia', 'Gunmen opened fire on a political figure''s convoy in Umuahia. The target survived but two aides were killed.', 'Umuahia, Abia', 'South East', 'Abia', 'Umuahia', 'critical', 'active', '2025-05-22 19:30:00', 1, '{"lat":5.5250,"lng":7.4950}', 'political', 1000, 'verified', 'text'),
('Child Labor Ring Uncovered in Cross River', 'Police uncovered a child labor ring in Calabar exploiting minors in quarries and farms. Dozens of children rescued.', 'Calabar, Cross River', 'South South', 'Cross River', 'Calabar', 'high', 'active', '2025-05-28 10:00:00', 1, '{"lat":4.9517,"lng":8.3417}', 'sgbv', 500, 'verified', 'text'),

-- June 2025
('IED Attack on Military Base in Borno', 'Suspected Boko Haram insurgents detonated IEDs near a military base in Maiduguri, causing casualties among soldiers.', 'Maiduguri, Borno', 'North East', 'Borno', 'Maiduguri', 'critical', 'active', '2025-06-01 05:00:00', 1, '{"lat":11.8311,"lng":13.1510}', 'terrorism', 5000, 'verified', 'text'),
('Fuel Scarcity Crisis in Abuja', 'Severe fuel scarcity in FCT causing long queues at filling stations. Businesses and transportation severely disrupted for weeks.', 'Abuja Municipal, FCT', 'North Central', 'FCT', 'Abuja Municipal', 'medium', 'resolved', '2025-06-05 07:00:00', 1, '{"lat":9.0765,"lng":7.3986}', 'economic', 100000, 'verified', 'text'),
('Bridge Collapse in Kogi', 'A major bridge in Lokoja collapsed under heavy traffic, plunging vehicles into the river. Search and rescue operations ongoing.', 'Lokoja, Kogi', 'North Central', 'Kogi', 'Lokoja', 'critical', 'resolved', '2025-06-10 11:00:00', 1, '{"lat":7.7974,"lng":6.7406}', 'infrastructure', 3000, 'verified', 'text'),
('Religious Tension in Kaduna', 'Rising religious tensions in Zaria following inflammatory preaching. Security agencies deployed to prevent escalation.', 'Zaria, Kaduna', 'North West', 'Kaduna', 'Zaria', 'medium', 'active', '2025-06-14 08:30:00', 1, '{"lat":11.0667,"lng":7.7000}', 'conflict', 25000, 'partially_verified', 'text'),
('Massive Flooding in Jigawa', 'Seasonal floods devastated communities in Dutse LGA, destroying farmlands and displacing over 10,000 people.', 'Dutse, Jigawa', 'North West', 'Jigawa', 'Dutse', 'high', 'active', '2025-06-18 15:00:00', 1, '{"lat":11.7566,"lng":9.3386}', 'natural_disaster', 30000, 'verified', 'text'),
('Armed Attack on Owerri Police Station', 'Unknown gunmen attacked a police station in Owerri, freeing suspects and destroying vehicles. IPOB suspected.', 'Owerri, Imo', 'South East', 'Imo', 'Owerri', 'critical', 'active', '2025-06-22 01:00:00', 1, '{"lat":5.4840,"lng":7.0351}', 'violence', 10000, 'verified', 'text'),
('Food Price Crisis in Kano', 'Sharp increase in food prices in Kano markets causing hardship. Residents struggling to afford basic staples like rice and maize.', 'Nassarawa, Kano', 'North West', 'Kano', 'Nassarawa', 'medium', 'active', '2025-06-28 09:00:00', 1, '{"lat":11.9833,"lng":8.5333}', 'economic', 80000, 'verified', 'web_form'),

-- July 2025
('Herder-Farmer Violence in Kwara', 'Deadly clash between herders and farmers in Ilorin over crop destruction by cattle. Multiple casualties and farms destroyed.', 'Ilorin, Kwara', 'North Central', 'Kwara', 'Ilorin', 'high', 'resolved', '2025-07-02 06:00:00', 1, '{"lat":8.4966,"lng":4.5426}', 'conflict', 10000, 'verified', 'text'),
('Warehouse Fire in Warri', 'A large warehouse containing petroleum products caught fire in Warri, Delta State. Firefighters battled the blaze for hours.', 'Warri, Delta', 'South South', 'Delta', 'Warri', 'high', 'resolved', '2025-07-06 21:00:00', 1, '{"lat":5.5167,"lng":5.7500}', 'infrastructure', 8000, 'verified', 'text'),
('Mass Kidnapping on Abuja-Kaduna Road', 'Bandits blocked the Abuja-Kaduna railway track and kidnapped passengers from a commercial vehicle. Over 20 victims taken.', 'Gwagwalada, FCT', 'North Central', 'FCT', 'Gwagwalada', 'critical', 'active', '2025-07-10 17:00:00', 1, '{"lat":8.9428,"lng":7.0839}', 'kidnapping', 2000, 'verified', 'text'),
('Meningitis Outbreak in Kebbi', 'Meningitis outbreak in Birnin Kebbi LGA with 150 confirmed cases and rising. Health workers deployed for vaccination campaign.', 'Birnin Kebbi, Kebbi', 'North West', 'Kebbi', 'Birnin Kebbi', 'critical', 'active', '2025-07-14 08:00:00', 1, '{"lat":12.4539,"lng":4.1975}', 'natural_disaster', 20000, 'verified', 'text'),
('Sit-at-Home Enforcement Violence in Enugu', 'Violent enforcement of Monday sit-at-home order in Nsukka led to destruction of vehicles and assault on traders.', 'Nsukka, Enugu', 'South East', 'Enugu', 'Nsukka', 'medium', 'active', '2025-07-18 08:30:00', 1, '{"lat":6.8567,"lng":7.3958}', 'political', 15000, 'partially_verified', 'text'),
('Water Pipeline Burst in Akure', 'Major water pipeline burst in Akure leaving thousands without water supply for weeks. Emergency repairs ongoing.', 'Akure, Ondo', 'South West', 'Ondo', 'Akure', 'medium', 'resolved', '2025-07-22 12:00:00', 1, '{"lat":7.2571,"lng":5.2058}', 'infrastructure', 35000, 'verified', 'text'),
('Domestic Violence Fatality in Surulere', 'Woman killed by spouse in domestic violence incident in Surulere, Lagos. Suspect arrested after neighbors intervened.', 'Surulere, Lagos', 'South West', 'Lagos', 'Surulere', 'high', 'resolved', '2025-07-28 23:00:00', 1, '{"lat":6.4969,"lng":3.3614}', 'sgbv', 500, 'verified', 'text'),

-- August 2025
('Bandit Attack on Mining Site in Zamfara', 'Armed bandits attacked an illegal mining site in Gusau, killing miners and seizing gold. Security forces in pursuit.', 'Gusau, Zamfara', 'North West', 'Zamfara', 'Gusau', 'critical', 'active', '2025-08-01 04:00:00', 1, '{"lat":12.1704,"lng":6.6642}', 'violence', 3000, 'verified', 'text'),
('Flooding Emergency in Lokoja', 'River Niger overflow caused catastrophic flooding in Lokoja, submerging entire neighborhoods. Emergency shelters set up.', 'Lokoja, Kogi', 'North Central', 'Kogi', 'Lokoja', 'critical', 'active', '2025-08-05 10:00:00', 1, '{"lat":7.7974,"lng":6.7406}', 'natural_disaster', 50000, 'verified', 'text'),
('Prison Break in Imo State', 'Inmates escaped from a correctional facility in Owerri after a coordinated attack by unknown gunmen. Manhunt launched.', 'Owerri, Imo', 'South East', 'Imo', 'Owerri', 'critical', 'active', '2025-08-08 02:00:00', 1, '{"lat":5.4840,"lng":7.0351}', 'violence', 20000, 'verified', 'text'),
('NLC Strike Paralyzes Osun State', 'Nigeria Labour Congress called an indefinite strike in Osogbo over unpaid salaries. Government offices and schools shut down.', 'Osogbo, Osun', 'South West', 'Osun', 'Osogbo', 'medium', 'resolved', '2025-08-12 07:00:00', 1, '{"lat":7.7667,"lng":4.5667}', 'protest', 60000, 'verified', 'web_form'),
('Pipeline Explosion in Delta', 'Oil pipeline explosion in Asaba killed three and injured dozens. Environmental contamination affecting water sources.', 'Asaba, Delta', 'South South', 'Delta', 'Asaba', 'critical', 'resolved', '2025-08-16 13:00:00', 1, '{"lat":6.1987,"lng":6.7337}', 'economic', 15000, 'verified', 'text'),
('Kidnapping of Traditional Ruler in Ebonyi', 'Gunmen kidnapped a traditional ruler in Abakaliki. Community leaders appealing for his safe release.', 'Abakaliki, Ebonyi', 'South East', 'Ebonyi', 'Abakaliki', 'high', 'active', '2025-08-20 20:00:00', 1, '{"lat":6.3249,"lng":8.1137}', 'kidnapping', 5000, 'verified', 'text'),
('Election Tribunal Violence in Gombe', 'Violence erupted outside election tribunal in Gombe as rival supporters clashed. Police fired tear gas to restore order.', 'Gombe, Gombe', 'North East', 'Gombe', 'Gombe', 'medium', 'resolved', '2025-08-25 14:00:00', 1, '{"lat":10.2897,"lng":11.1689}', 'political', 8000, 'verified', 'text'),

-- September 2025
('Boko Haram Suicide Bombing in Maiduguri', 'Suicide bomber detonated explosives at a busy market in Maiduguri, killing at least 15 people and injuring dozens more.', 'Maiduguri, Borno', 'North East', 'Borno', 'Maiduguri', 'critical', 'active', '2025-09-01 11:00:00', 1, '{"lat":11.8311,"lng":13.1510}', 'terrorism', 20000, 'verified', 'text'),
('Erosion Disaster in Ado-Ekiti', 'Severe erosion washed away parts of a major road in Ado-Ekiti, isolating communities and disrupting transportation.', 'Ado-Ekiti, Ekiti', 'South West', 'Ekiti', 'Ado-Ekiti', 'high', 'active', '2025-09-05 16:00:00', 1, '{"lat":7.6211,"lng":5.2200}', 'natural_disaster', 12000, 'verified', 'text'),
('Communal Violence in Jos North', 'Renewed communal violence in Jos North between settler and indigene communities. Curfew imposed, military patrolling streets.', 'Jos North, Plateau', 'North Central', 'Plateau', 'Jos North', 'high', 'active', '2025-09-09 05:00:00', 1, '{"lat":9.8965,"lng":8.8583}', 'conflict', 30000, 'verified', 'text'),
('Cyber Fraud Ring Busted in Lagos', 'EFCC arrested 45 suspected internet fraudsters in a raid on a Lagos Island apartment complex. Equipment and cash seized.', 'Lagos Island, Lagos', 'South West', 'Lagos', 'Lagos Island', 'medium', 'resolved', '2025-09-13 06:00:00', 1, '{"lat":6.4541,"lng":3.3947}', 'economic', 1000, 'verified', 'text'),
('Armed Robbery Spree in Calabar', 'Series of armed robberies in Calabar over three days targeting banks and businesses. Security heightened across the city.', 'Calabar, Cross River', 'South South', 'Cross River', 'Calabar', 'high', 'active', '2025-09-17 22:00:00', 1, '{"lat":4.9517,"lng":8.3417}', 'violence', 10000, 'verified', 'text'),
('Protest Over Police Brutality in Abuja', 'Thousands marched in Abuja protesting police brutality following the death of a young man in custody. Tear gas deployed.', 'Abuja Municipal, FCT', 'North Central', 'FCT', 'Abuja Municipal', 'medium', 'resolved', '2025-09-21 10:00:00', 1, '{"lat":9.0765,"lng":7.3986}', 'protest', 50000, 'verified', 'web_form'),
('Child Marriage Intervention in Jigawa', 'NGOs intervened to prevent forced marriage of a 13-year-old girl in Dutse. Legal proceedings initiated against parents.', 'Dutse, Jigawa', 'North West', 'Jigawa', 'Dutse', 'medium', 'active', '2025-09-28 09:00:00', 1, '{"lat":11.7566,"lng":9.3386}', 'sgbv', 500, 'partially_verified', 'voice'),

-- October 2025
('Tanker Fire on Third Mainland Bridge Lagos', 'A petrol tanker caught fire on Third Mainland Bridge causing major traffic disruption and panic. Bridge closed for hours.', 'Lagos Island, Lagos', 'South West', 'Lagos', 'Lagos Island', 'high', 'resolved', '2025-10-02 14:30:00', 1, '{"lat":6.4541,"lng":3.3947}', 'infrastructure', 100000, 'verified', 'text'),
('Bandits Kill Villagers in Kaduna', 'Armed bandits killed 25 people in coordinated attacks on three villages in Kaduna North. Military launched counter-offensive.', 'Kaduna North, Kaduna', 'North West', 'Kaduna', 'Kaduna North', 'critical', 'active', '2025-10-06 03:00:00', 1, '{"lat":10.5167,"lng":7.4333}', 'violence', 8000, 'verified', 'text'),
('Flooding Displaces Thousands in Adamawa', 'River Benue burst its banks flooding communities in Yola North. Over 5,000 people displaced, homes and crops destroyed.', 'Yola North, Adamawa', 'North East', 'Adamawa', 'Yola North', 'high', 'active', '2025-10-10 08:00:00', 1, '{"lat":9.2094,"lng":12.4807}', 'natural_disaster', 25000, 'verified', 'text'),
('Political Rally Stampede in Kano', 'Stampede at a political rally in Kano Municipal killed 8 people and injured dozens. Overcrowding blamed for the incident.', 'Kano Municipal, Kano', 'North West', 'Kano', 'Kano Municipal', 'high', 'resolved', '2025-10-14 15:00:00', 1, '{"lat":12.0022,"lng":8.5920}', 'political', 15000, 'verified', 'text'),
('Gas Explosion in Abeokuta', 'Gas cylinder explosion at a residential building in Abeokuta killed a family of five. Neighbors'' homes also damaged.', 'Abeokuta, Ogun', 'South West', 'Ogun', 'Abeokuta', 'high', 'resolved', '2025-10-18 19:00:00', 1, '{"lat":7.1475,"lng":3.3619}', 'infrastructure', 2000, 'verified', 'text'),
('Oil Theft Operation Busted in Bayelsa', 'Navy busted a major illegal oil bunkering operation in Yenagoa seizing vessels and arresting operators. Millions in crude recovered.', 'Yenagoa, Bayelsa', 'South South', 'Bayelsa', 'Yenagoa', 'medium', 'resolved', '2025-10-22 06:00:00', 1, '{"lat":4.9267,"lng":6.2676}', 'economic', 5000, 'verified', 'text'),
('Kidnapping of Priest in Akwa Ibom', 'Catholic priest kidnapped from his parish in Uyo. Diocese appealing for his safe return. Ransom demands made.', 'Uyo, Akwa Ibom', 'South South', 'Akwa Ibom', 'Uyo', 'high', 'active', '2025-10-28 21:00:00', 1, '{"lat":5.0378,"lng":7.9085}', 'kidnapping', 3000, 'verified', 'text'),

-- November 2025
('Warehouse Explosion in Port Harcourt', 'Chemical warehouse explosion in Port Harcourt caused significant damage to surrounding buildings. Dozens hospitalized with burns.', 'Port Harcourt, Rivers', 'South South', 'Rivers', 'Port Harcourt', 'critical', 'resolved', '2025-11-01 08:00:00', 1, '{"lat":4.8156,"lng":7.0498}', 'infrastructure', 10000, 'verified', 'text'),
('Farmer-Herder Killings in Gboko', 'Herders attacked farming community in Gboko, Benue State killing 12 people including women and children. Military deployed.', 'Gboko, Benue', 'North Central', 'Benue', 'Gboko', 'critical', 'active', '2025-11-05 04:30:00', 1, '{"lat":7.3230,"lng":9.0007}', 'conflict', 8000, 'verified', 'text'),
('Drug Cartel Bust in Lagos', 'NDLEA busted a major drug cartel operating from Surulere, seizing cocaine and tramadol worth billions. Multiple arrests made.', 'Surulere, Lagos', 'South West', 'Lagos', 'Surulere', 'high', 'resolved', '2025-11-08 03:00:00', 1, '{"lat":6.4969,"lng":3.3614}', 'violence', 5000, 'verified', 'text'),
('University Protest Turns Violent in Abia', 'Student protest at Abia State University in Umuahia turned violent as police fired live rounds. Several students hospitalized.', 'Umuahia, Abia', 'South East', 'Abia', 'Umuahia', 'high', 'active', '2025-11-12 11:00:00', 1, '{"lat":5.5250,"lng":7.4950}', 'protest', 10000, 'verified', 'web_form'),
('Windstorm Destroys Market in Ogbomoso', 'Severe windstorm destroyed a major market and dozens of homes in Ogbomoso. Traders lost goods worth millions.', 'Ogbomoso, Oyo', 'South West', 'Oyo', 'Ogbomoso', 'high', 'resolved', '2025-11-16 17:00:00', 1, '{"lat":8.1335,"lng":4.2407}', 'natural_disaster', 15000, 'verified', 'text'),
('Assassination of Council Chairman in Kogi', 'Local government council chairman assassinated by gunmen in Lokoja. Political motive suspected, investigation ongoing.', 'Lokoja, Kogi', 'North Central', 'Kogi', 'Lokoja', 'critical', 'active', '2025-11-20 20:00:00', 1, '{"lat":7.7974,"lng":6.7406}', 'political', 5000, 'verified', 'text'),
('Rape Case Sparks Outrage in Owerri', 'Brutal rape of a university student in Owerri sparked protests and demands for justice. Suspect arrested after public outcry.', 'Owerri, Imo', 'South East', 'Imo', 'Owerri', 'high', 'active', '2025-11-25 22:00:00', 1, '{"lat":5.4840,"lng":7.0351}', 'sgbv', 8000, 'verified', 'voice'),
('Illegal Mining Collapse in Plateau', 'Illegal tin mining site collapsed in Jos North, trapping and killing at least 8 miners. Rescue operations hampered by terrain.', 'Jos North, Plateau', 'North Central', 'Plateau', 'Jos North', 'high', 'resolved', '2025-11-28 09:00:00', 1, '{"lat":9.8965,"lng":8.8583}', 'infrastructure', 2000, 'verified', 'text'),

-- December 2025
('Christmas Eve Terrorist Attack in Borno', 'Terrorists attacked a community gathering on Christmas Eve in Maiduguri. Multiple casualties among civilians celebrating.', 'Maiduguri, Borno', 'North East', 'Borno', 'Maiduguri', 'critical', 'active', '2025-12-24 19:00:00', 1, '{"lat":11.8311,"lng":13.1510}', 'terrorism', 15000, 'verified', 'text'),
('New Year Fire at Surulere Market', 'Fire destroyed sections of a market in Surulere on New Year''s Eve. Traders lost goods stockpiled for the festive season.', 'Surulere, Lagos', 'South West', 'Lagos', 'Surulere', 'high', 'resolved', '2025-12-31 23:30:00', 1, '{"lat":6.4969,"lng":3.3614}', 'economic', 10000, 'verified', 'text'),
('Highway Robbery Spree in Edo', 'Armed robbers terrorized travelers on Benin-Ore expressway over the holiday period. Multiple vehicles hijacked.', 'Benin City, Edo', 'South South', 'Edo', 'Benin City', 'high', 'active', '2025-12-27 16:00:00', 1, '{"lat":6.3350,"lng":5.6037}', 'violence', 5000, 'verified', 'text'),
('Communal Clash in Ebonyi', 'Long-standing boundary dispute between communities in Abakaliki erupted into violence. Houses burned and residents displaced.', 'Abakaliki, Ebonyi', 'South East', 'Ebonyi', 'Abakaliki', 'high', 'active', '2025-12-20 07:00:00', 1, '{"lat":6.3249,"lng":8.1137}', 'conflict', 10000, 'verified', 'text'),
('Cholera Outbreak in Gombe', 'Cholera outbreak in Gombe LGA with over 100 cases reported. Contaminated water sources identified as cause.', 'Gombe, Gombe', 'North East', 'Gombe', 'Gombe', 'high', 'active', '2025-12-15 08:00:00', 1, '{"lat":10.2897,"lng":11.1689}', 'natural_disaster', 20000, 'verified', 'text'),
('Protest Against Electoral Violence', 'Citizens in multiple cities protested against electoral violence and rigging. Largest demonstrations in Abuja and Lagos.', 'Abuja Municipal, FCT', 'North Central', 'FCT', 'Abuja Municipal', 'medium', 'resolved', '2025-12-10 10:00:00', 1, '{"lat":9.0765,"lng":7.3986}', 'protest', 80000, 'verified', 'web_form'),
('Kidnapping Ring Busted in Ogun', 'Police dismantled a kidnapping syndicate in Abeokuta, rescuing 8 victims and arresting 12 suspects including a police officer.', 'Abeokuta, Ogun', 'South West', 'Ogun', 'Abeokuta', 'high', 'resolved', '2025-12-05 05:00:00', 1, '{"lat":7.1475,"lng":3.3619}', 'kidnapping', 3000, 'verified', 'text'),

-- January 2026
('New Year Attack on Zamfara Town', 'Bandits launched a coordinated attack on Gusau town in the early hours of January 2nd, targeting residential areas.', 'Gusau, Zamfara', 'North West', 'Zamfara', 'Gusau', 'critical', 'active', '2026-01-02 02:00:00', 1, '{"lat":12.1704,"lng":6.6642}', 'violence', 12000, 'verified', 'text'),
('Flooding After Dam Release in Niger', 'Emergency flooding in Minna after dam water release upstream. Thousands evacuated from low-lying areas.', 'Minna, Niger', 'North Central', 'Niger', 'Minna', 'high', 'active', '2026-01-06 14:00:00', 1, '{"lat":9.6138,"lng":6.5569}', 'natural_disaster', 25000, 'verified', 'text'),
('IPOB Sit-at-Home Enforcement in Anambra', 'Violent enforcement of sit-at-home order in Onitsha disrupted businesses. Vehicles set ablaze and traders assaulted.', 'Onitsha, Anambra', 'South East', 'Anambra', 'Onitsha', 'medium', 'active', '2026-01-10 08:00:00', 1, '{"lat":6.1495,"lng":6.7882}', 'political', 30000, 'partially_verified', 'text'),
('Armed Attack on Mining Community in Plateau', 'Gunmen attacked a mining community in Jos South, killing workers and stealing equipment. Security forces deployed.', 'Jos South, Plateau', 'North Central', 'Plateau', 'Jos South', 'high', 'active', '2026-01-14 04:00:00', 1, '{"lat":9.8675,"lng":8.8961}', 'violence', 5000, 'verified', 'text'),
('Oil Spill Emergency in Akwa Ibom', 'Major oil spill from offshore facility contaminated fishing waters in Uyo area. Fishermen''s livelihoods threatened.', 'Uyo, Akwa Ibom', 'South South', 'Akwa Ibom', 'Uyo', 'high', 'active', '2026-01-18 10:00:00', 1, '{"lat":5.0378,"lng":7.9085}', 'economic', 15000, 'verified', 'text'),
('University Staff Strike in Kwara', 'ASUU declared a 2-week warning strike in Ilorin over inadequate funding. Students stranded as campuses shut.', 'Ilorin, Kwara', 'North Central', 'Kwara', 'Ilorin', 'medium', 'active', '2026-01-22 07:00:00', 1, '{"lat":8.4966,"lng":4.5426}', 'protest', 40000, 'verified', 'web_form'),
('Gender Violence Awareness March in Lagos', 'Thousands marched in Ikeja demanding stronger laws against gender-based violence following a string of domestic abuse cases.', 'Ikeja, Lagos', 'South West', 'Lagos', 'Ikeja', 'low', 'resolved', '2026-01-26 09:00:00', 1, '{"lat":6.5964,"lng":3.3425}', 'sgbv', 20000, 'verified', 'web_form'),

-- February 2026
('Boko Haram Raid on Yobe Village', 'Boko Haram militants raided a village near Damaturu, abducting women and looting food stores. Military responding.', 'Damaturu, Yobe', 'North East', 'Yobe', 'Damaturu', 'critical', 'active', '2026-02-01 03:00:00', 1, '{"lat":11.7471,"lng":11.9609}', 'terrorism', 8000, 'verified', 'text'),
('Market Demolition Protest in Abuja', 'Traders protested the demolition of their market stalls in Gwagwalada by the FCT authorities. Clash with security forces ensued.', 'Gwagwalada, FCT', 'North Central', 'FCT', 'Gwagwalada', 'medium', 'active', '2026-02-05 10:00:00', 1, '{"lat":8.9428,"lng":7.0839}', 'protest', 10000, 'verified', 'text'),
('Road Collapse in Enugu', 'Major road collapse in Enugu North following heavy rains. Commuters stranded and businesses cut off from supply routes.', 'Enugu North, Enugu', 'South East', 'Enugu', 'Enugu North', 'medium', 'active', '2026-02-09 15:00:00', 1, '{"lat":6.4402,"lng":7.4994}', 'infrastructure', 15000, 'verified', 'text'),
('Kidnapping of Oil Workers in Rivers', 'Five expatriate oil workers kidnapped from a flow station in Obio-Akpor. Company negotiating with abductors.', 'Obio-Akpor, Rivers', 'South South', 'Rivers', 'Obio-Akpor', 'critical', 'active', '2026-02-13 06:00:00', 1, '{"lat":4.8896,"lng":6.9569}', 'kidnapping', 5000, 'verified', 'text'),
('Ethnic Tension Escalates in Taraba', 'Escalating ethnic tensions between communities in Jalingo over political appointments. Security agencies on alert.', 'Jalingo, Taraba', 'North East', 'Taraba', 'Jalingo', 'medium', 'active', '2026-02-17 08:00:00', 1, '{"lat":8.8932,"lng":11.3598}', 'conflict', 20000, 'partially_verified', 'text'),
('Fire at Kano Textile Market', 'Massive fire gutted the famous textile market in Kano Municipal, destroying goods worth billions. Thousands of traders affected.', 'Kano Municipal, Kano', 'North West', 'Kano', 'Kano Municipal', 'high', 'active', '2026-02-21 01:00:00', 1, '{"lat":12.0022,"lng":8.5920}', 'economic', 50000, 'verified', 'text'),
('Bandit Kidnapping in Katsina', 'Over 50 villagers kidnapped by bandits in Katsina LGA during a midnight raid. Governor calls for military intervention.', 'Katsina, Katsina', 'North West', 'Katsina', 'Katsina', 'critical', 'active', '2026-02-25 00:30:00', 1, '{"lat":12.9908,"lng":7.6008}', 'kidnapping', 10000, 'verified', 'text'),
('Building Collapse in Aba', 'Two-story building under construction collapsed in Aba North trapping workers. Emergency services extracting survivors.', 'Aba North, Abia', 'South East', 'Abia', 'Aba North', 'high', 'pending', '2026-02-28 13:00:00', 1, '{"lat":5.1215,"lng":7.3698}', 'infrastructure', 1500, 'unverified', 'sms');
